site:
    resource: ../../src/Security/WebsiteAuthenticator.php
    type: annotation
    prefix: /

controllers:
    resource: ../../src/Controller/
    type: annotation

admin:
    resource: ../../src/Controller/AdminController.php
    type: annotation
    prefix: /admin

blogs:
    resource: ../../src/Controller/BlogController.php
    type: annotation
    prefix: /blog

profiles:
    resource: ../../src/Controller/ProfileController.php
    type: annotation
    prefix: /profile

comments:
    resource: ../../src/Controller/CommentController.php
    type: annotation
    prefix: /comment

inventory:
    resource: ../../src/Controller/InventoryController.php
    type: annotation
    prefix: /gallery

element:
    resource: ../../src/Controller/ElementController.php
    type: annotation
    prefix: /element

util:
    resource: ../../src/Controller/UtilJSController.php
    type: annotation
    prefix: /util

kernel:
    resource: ../../src/Kernel.php
    type: annotation
