login:
    path: /login
    controller: App\Controller\SecurityController::signin

logout:
    path: /logout
    controller: App\Controller\SecurityController::signin

homepage:
    path: /
    controller: App\Controller\BlogController::indexAction

admin:
    path: /admin
    controller: App\Controller\AdminController

blog:
    path: /blog
    controller: App\Controller\BlogController

comment:
    path: /comment
    controller: App\Controller\CommentController

profile:
    path: /profile
    controller: App\Controller\ProfileController

inventory:
    path: /gallery
    controller: App\Controller\InventoryController

element:
    path: /element
    controller: App\Controller\ElementController

util:
    path: /util
    controller: App\Controller\UtilJSController